Add UNSAFE_BUFFERS to some lines in checked_iterators_nocompile.nc
After https://github.com/llvm/llvm-project/pull/198006 we're seeing

```
python3 ../../tools/nocompile/wrapper.py ../../third_party/llvm-build/Release+Asserts/bin/clang++ ../../base/containers/checked_iterators_noco...(too long)
error: 'expected-error' diagnostics seen but not expected:
  File ../../base/containers/checked_iterators_nocompile.nc Line 16: function introduces unsafe buffer manipulation
  File ../../base/containers/checked_iterators_nocompile.nc Line 16: unsafe pointer arithmetic
  File ../../base/containers/checked_iterators_nocompile.nc Line 20: function introduces unsafe buffer manipulation
  File ../../base/containers/checked_iterators_nocompile.nc Line 20: unsafe pointer arithmetic
  File ../../base/containers/checked_iterators_nocompile.nc Line 21: unsafe pointer arithmetic
5 errors generated.
```

which looks valid.

Bug: 516873015
Change-Id: I9bcf6a06d7663d31c2761c47ae565fc3c12b746a
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/7879371
Reviewed-by: Hans Wennborg <hans@chromium.org>
Reviewed-by: Daniel Cheng <dcheng@chromium.org>
Commit-Queue: Daniel Cheng <dcheng@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1637049}


CrOS-Libchrome-Original-Commit: cbc4841f1dcc8ec17a0581d6d7b12a79c9fdc2f8