Revert "Use string_view in logging and trace_event location"
This reverts commit 5439f8eb1e170ce515a12e211b5d20a2bff75ea5.

Reason for revert: Causing CQ failure:
https://ci.chromium.org/ui/p/chromium/builders/ci/Libfuzzer%20Upload%20Chrome%20OS%20ASan/120721/overview

Step compile failed. Error logs are shown below:
[72328/76374] CXX obj/chrome/browser/ash/policy/remote_commands/policy_remote_commands_fuzzer/remote_commands_fuzzer.o
../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/chrome/browser/ash/policy/remote_commands/policy_remote_commands_fuzzer/...(too long)
../../chrome/browser/ash/policy/remote_commands/remote_commands_fuzzer.cc:56:35: error: cannot initialize a parameter of type 'LogMessageHandlerFunction' (aka 'bool (*)(int, basic_string_view<char>, int, unsigned long, const basic_string<char> &)') with an rvalue of type 'bool (*)(int, const char *, int, size_t, const std::string &)' (aka 'bool (*)(int, const char *, int, unsigned long, const basic_string<char> &)'): type mismatch at 2nd parameter ('std::string_view' (aka 'basic_string_view<char>') vs 'const char *')
   56 |     logging::SetLogMessageHandler(&VoidifyingLogHandler);
      |                                   ^~~~~~~~~~~~~~~~~~~~~

Original change's description:
> Use string_view in logging and trace_event location
>
> Changes the LogMessage class to use a string_view for file names. This
> required a matching change in trace_event: a const char* string was
> passed from logging code, but there is no safe way to get a const
> char* from a string_view since the latter may not be null-terminated.
>
> Many clients of base/logging.h are updated to use string_view as well.
>
> Code which attempts to pass a string_view to a LogMessage by its data
> pointer already exists:
> https://source.chromium.org/chromium/chromium/src/+/main:ash/quick_pair/common/logging.cc;l=49;drc=c6c99d03b1d2f4fab91d6be8665f81b540690c73
> https://source.chromium.org/chromium/chromium/src/+/main:components/cross_device/logging/logging.cc;l=30;drc=00704dbac4f63b2476aac319572ffc42c9b71fc2
>
> Desire for Rust logging support prompted this change. In principle a
> Rust log facility can be a thin wrapper around the base logging
> implementation, but Rust has almost no support for null-terminated
> strings. Instead, Rust provides a string_view equivalent built in to
> the language. This change enables Rust code to pass file names
> obtained by language-specific macros to the C++ implementation.
>
> Bug: None
> Change-Id: I21b4f1c945b70d54f66d80adf3dcda1fe5a39f71
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5765705
> Reviewed-by: Peter Boström <pbos@chromium.org>
> Auto-Submit: Collin Baker <collinbaker@chromium.org>
> Commit-Queue: Collin Baker <collinbaker@chromium.org>
> Reviewed-by: Stephen Nusko <nuskos@chromium.org>
> Reviewed-by: Daniel Cheng <dcheng@chromium.org>
> Owners-Override: Daniel Cheng <dcheng@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1436283}

Bug: None
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Change-Id: Ic5ea70ca431742aac41c270e99937710413f0fd8
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6383699
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Auto-Submit: Fred Shih <ffred@chromium.org>
Commit-Queue: Fred Shih <ffred@chromium.org>
Owners-Override: Fred Shih <ffred@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1436375}


CrOS-Libchrome-Original-Commit: 3a5760fc0ab3fe453c89d6357512e69cf9592196