Guard conflicting pthread_mutexattr_setprotocol with IS_ANDROID
Newer versions of glibc provide a different declaration
causing a build error.

../../base/synchronization/lock_impl_posix.cc:26:27: error: conflicting declaration of C function ‘int pthread_mutexattr_setprotocol(pthread_mutexattr_t*)’
   26 | int __attribute__((weak)) pthread_mutexattr_setprotocol(
      |                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/c++/15/x86_64-suse-linux/bits/gthr-default.h:35,
                 from /usr/include/c++/15/x86_64-suse-linux/bits/gthr.h:157,
                 from /usr/include/c++/15/ext/atomicity.h:37,
                 from /usr/include/c++/15/bits/ios_base.h:41,
                 from /usr/include/c++/15/ios:46,
                 from /usr/include/c++/15/bits/ostream.h:43,
                 from /usr/include/c++/15/bits/unique_ptr.h:43,
                 from /usr/include/c++/15/memory:80,
                 from ../../base/check.h:9,
                 from ../../base/synchronization/lock_impl.h:11,
                 from ../../base/synchronization/lock_impl_posix.cc:5:
/usr/include/pthread.h:913:12: note: previous declaration ‘int pthread_mutexattr_setprotocol(pthread_mutexattr_t*, int)’
  913 | extern int pthread_mutexattr_setprotocol (pthread_mutexattr_t *__attr,
      |

Change-Id: Iebbe0b7261c0eff9a2dab92a156914c9098b8275
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6921906
Commit-Queue: Anand Ravi <anandrv@google.com>
Auto-Submit: Bruno Pitrus <brunopitrus@hotmail.com>
Reviewed-by: Kyle Charbonneau <kylechar@chromium.org>
Reviewed-by: Anand Ravi <anandrv@google.com>
Cr-Commit-Position: refs/heads/main@{#1516010}


CrOS-Libchrome-Original-Commit: c01fca7822f286bcbbfd882e890edab2ef6ae966