Add missing include for `base/command_line.h` in base/feature_list.cc
The https://crrev.com/c/6885575 broke the builders with
DCHECK_IS_CONFIGURABLE. E.g.
https://ci.chromium.org/ui/p/chrome/builders/official/android-x86-official-dcheck/1840/overview

```
../../base/feature_list.cc:632:7: error: incomplete type 'base::CommandLine' named in nested name specifier
  632 |       CommandLine::ForCurrentProcess()->HasSwitch(
      |       ^~~~~~~~~~~~~
```

Fixed: 441558006
Change-Id: I3640b7e9a8df1bf5cfc1458ae434667a2f919567
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6892022
Commit-Queue: Zijie He <zijiehe@google.com>
Reviewed-by: Lei Zhang <thestig@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1507383}


CrOS-Libchrome-Original-Commit: fd8a14ee30e6846c2f6ca1bd31814649df5b202d